### ISSUE TITLE
Valor decimal

### ISSUE THREAD

**Issue by degabri** [feliperafael/fundamentus-data-scraping#2]
Ao importar os valores do arquivo html não está tratando adequadamente os valores decimais. Ex: Se a cotação da ação é 30,45 o valor transcrito para o csv fica sendo 3045 (valor sem a vírgula).

**Comment by degabri** [comment]
Essa alteracao  resolve

df = pd.read_html(str(tables).replace('?', ''),decimal=',',thousands='.')

**Comment by feliperafael** [comment]
Obrigado pela observação @degabri. Também resolve caso você salve o df setando um separador diferente de , (como por exemplo sep=';') 

df_final.to_csv('output/{}.csv'.format(papel), index=False, header=False, sep=';')

Irei adicionar a sua sugestão ao código.
